### ISSUE TITLE
Tracking: 支持更多语言

### ISSUE THREAD

**Issue by RinChanNOWWW** [OpenBUPT/session#1]
- [x] 支持 Python: https://github.com/OpenBUPT/session/pull/5
- [ ] 支持 JS/TS: https://github.com/OpenBUPT/session/issues/3
- [x] 支持 Go: https://github.com/OpenBUPT/session/issues/6

待补充……
